name: deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  REPO_URL: "https://github.com/Stijnc/AzureEats-Website"
  TF_VAR_resource_group_name: "rg-tfazure2020"
  TF_VAR_owner: "stijnc"
  TF_VAR_project: "tfazure2020"
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  platform-deploy:
    name: platform deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infrastructure/tf
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: terraform init
        id: init
        run: terraform init -backend-config="env/backend.tfvars"

      - name: terraform validate
        id: validate
        run: terraform validate -no-color

      - name: terraform plan
        id: plan
        run: terraform plan -no-color

      - name: terraform apply
        if: contains(github.ref, 'master') && github.event_name == 'push'
        id: apply
        run: terraform apply -auto-approve -no-color

        #Needs help
      - name: terraform output
        id: out
        run: |
          terraform output app_service_name
        continue-on-error: true

      - name: continious deployment
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: |
            az webapp deployment source config --branch ${{ GITHUB_REF#refs/heads/ }} --manual-integration --name ${{ steps.out.outputs.stdout }} --repo-url ${{ env.REPO_URL }} --resource-group ${{ env.TF_VAR_resource_group_name}}
