name: deploy
on:
    push:
        branches:
            - master
env:
    GITHUB_PAT : ${{ secrets.PAT}}
    REPO_URL : "https://github.com/Stijnc/AzureEats-Website"
    TF_VAR_resource_group_name : "rg-tfazure2020"
    TF_VAR_owner : "stijnc"
    TF_VAR_project : "tfazure2020"
    ARM_CLIENT_ID : ${{ secrets.ARM_CLIENT_ID }}
    ARM_CLIENT_SECRET : ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_TENANT_ID : ${{ ARM_TENANT_ID }}
    ARM_SUBSCRIPTION_ID : ${{ ARM_SUBSCRIPTION_ID }}

jobs:
    platform-deploy:
        name: platform deployment
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: infrastructre/tf
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 0.12.26
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: terraform fmt
              run: terraform fmt

            - name: terraform init
              run: terraform init -backend-config="env/backend.tfvars"

            - name: terraform validate
              run: terraform validate -no-color

            - name: terraform plan
              run: terraform plan -no-color

            - name: terraform apply
              run: terraform apply -auto-approve -no-color

            - name : terraform output
              run: echo ::set-output name=tf_out::$(terraform output -json)

            - name: continious deployment
              uses: Azure/cli@v1.0.0
              env: 
                tf_out : ${{steps.set.outputs.tf_out}}
              with:
                inlineScript: |
                  az webapp deployment source config --branch master --manual-integration --name $($tf_out | jq '.app_service_name.value.') --repo-url $REPO_URL --resource-group $TF_VAR_resource_group_name
    
            